/**
 * Todo texto visível ao usuário vive aqui (regra 2 do CLAUDE.md).
 *
 * Nenhum componente em `src/` pode conter string literal renderizada em JSX.
 * Termos em inglês usados abaixo vêm de `glossary.ts` e não são traduzidos.
 */

export const strings = {
  app: {
    name: 'KEPLER',
    provider: 'Monoda Consulting Group',
    client: 'Verene Energia',
    descriptor: 'Plataforma agêntica de dados',
  },
  screens: {
    home: {
      wordmark: 'KEPLER',
    },
    styleguide: {
      title: 'Design system',
      subtitle: 'Tokens, superfícies e componentes do KEPLER',
      surfaceLabel: 'Superfície',
      surfaceInk: 'Escura (cockpit)',
      surfacePaper: 'Clara (documento)',
      sections: {
        palette: 'Paleta base',
        paletteNote:
          'Os nove valores do deck Galaxy. Imutáveis: componentes não usam estas cores diretamente, usam os tokens semânticos derivados delas.',
        semantic: 'Tokens semânticos',
        semanticNote:
          'Resolvem por superfície. verene-violet reprova sobre a superfície escura (2,36:1) e signal-green reprova sobre a clara (2,08:1) — por isso o token troca de valor, e não a regra de uso.',
        typography: 'Tipografia',
        typographyNote:
          'Jost, geométrica, substituta web da Century Gothic do deck. Números sempre tabulares.',
        buttons: 'Botões',
        badges: 'Estados',
        badgesNote: 'Matizes quentes e o neutro frio marcam situação. Sempre com rótulo — cor nunca é o único portador de significado.',
        defects: 'Origem de defeito',
        defectsNote:
          'Escala categórica em matizes frios, separada por matiz e por luminância. Distinta da escala de estado, que é quente.',
        table: 'Tabela densa',
        tableNote: 'Linha de 28px, números tabulares, alinhamento à direita em toda coluna numérica.',
        logos: 'Logos',
        logosNote: 'Slots reservados. Os arquivos atuais são placeholders e seguem a cor da superfície.',
      },
      table: {
        columns: {
          object: 'Objeto',
          records: 'Registros',
          migrated: 'Migrados',
          defects: 'Defeitos',
          rate: 'Aderência',
          origin: 'Origem',
          state: 'Situação',
        },
      },
      typeSamples: {
        pageTitle: 'Título de tela',
        sectionTitle: 'Título de seção',
        body: 'Texto corrido em corpo de 13px, a medida padrão da interface.',
        small: 'Texto de apoio em 12px',
        label: 'RÓTULO EM 11PX',
        micro: 'MICRO 10PX',
        numerals: 'Numerais tabulares',
        // dois runs de mesmo comprimento: com tnum as colunas coincidem
        numeralsSampleA: '1234567890',
        numeralsSampleB: '1111111111',
      },
      buttonSamples: {
        primary: 'Executar playbook',
        secondary: 'Ver manifest',
        ghost: 'Cancelar',
        disabled: 'Indisponível',
      },
      swatch: {
        onInk: 'sobre escura',
        onPaper: 'sobre clara',
        contrast: 'contraste',
      },
    },
  },
  states: {
    signed: 'Assinado',
    held: 'Retido',
    exception: 'Exceção aberta',
    'pending-gate': 'Aguardando Gate',
  },
  defects: {
    'defect-source': 'Origem',
    'defect-transformation': 'Transformação',
    'defect-target-config': 'Configuração de destino',
    'defect-load': 'Carga',
  },
  brands: {
    verene: 'Verene Energia',
    monoda: 'Monoda Consulting Group',
  },
  // Símbolos e separadores também são texto visível: entram aqui, não no JSX.
  simbolos: {
    porcento: '%',
    separador: ' · ',
    doisPontos: ': ',
  },
  shell: {
    projectTitle: 'GALAXY | Transformação de Dados',
    playbookLabel: 'playbook',
    cycleLabel: 'Ciclo',
    navLabel: 'Telas',
    skipToContent: 'Ir para o conteúdo',
  },
  nav: {
    missionControl: 'Mission Control',
    playbook: 'Playbook',
    mapping: 'Dicionário de mapeamento',
    styleguide: 'Design system',
  },
  ruleTypes: {
    format: 'Formato',
    domain: 'Domínio',
    length: 'Comprimento',
    referential: 'Referencial',
    conversion: 'Conversão',
    derivation: 'Derivação',
    business: 'Negócio',
    survivorship: 'Sobrevivência',
  },
  ruleStatus: {
    active: 'Ativa',
    candidate: 'Candidata',
    deprecated: 'Aposentada',
  },
  ruleNature: {
    deterministic: 'Determinística',
    generative: 'Generativa',
  },
  migrationObjects: {
    'business-partner': 'Business Partner (fornecedor)',
    'product-master': 'Product master',
    'service-master': 'Service master',
    'outline-agreement': 'Outline agreement',
    'purchase-order': 'Purchase order',
    'purchase-requisition': 'Purchase requisition',
    stock: 'Posições de estoque',
  },
  packageStates: {
    'nao-iniciado': 'Não iniciado',
    'em-processamento': 'Em processamento',
    retido: 'Retido',
    'aguardando-gate': 'Aguardando Gate',
    aprovado: 'Aprovado',
  },
  qualityDimensions: {
    completude: 'Completude',
    validade: 'Validade',
    unicidade: 'Unicidade',
    consistencia: 'Consistência',
    conformidade: 'Conformidade',
    precisao: 'Precisão',
  },
  agentActivity: {
    concluido: 'Concluído',
    'em-execucao': 'Em execução',
    bloqueado: 'Bloqueado',
    aguardando: 'Aguardando',
    continuo: 'Contínuo',
  },
  missionControl: {
    title: 'Mission Control',
    subtitle: 'Escopo, recebimento, qualidade e agentes em um lugar só',
    grid: {
      title: 'Pacotes de carga',
      note: 'Seis objetos, quatro SPEs, dois ciclos. Quarenta e oito pacotes — este é o escopo inteiro, não uma amostra. O número em cada célula é o volume previsto do pacote.',
      colObjeto: 'Objeto',
      colTotal: 'Volume',
      legenda: 'Estado',
      resumoPacotes: 'pacotes',
      resumoRegistros: 'registros no escopo',
    },
    waves: {
      title: 'Plano de ondas',
      note: 'A ordem não é arbitrária: documento transacional aponta para cadastro. Migrar fora de ordem é criar referência para o que ainda não existe.',
      objetosLabel: 'Objetos',
      dependenciaLabel: 'Por que nesta posição',
      volumeLabel: 'Volume',
      waveLabel: 'Wave',
    },
    defects: {
      title: 'Mapa de defeitos',
      note: 'Perfilagem do VEGA sobre o que já foi recebido. Taxa é defeitos por cem registros; um registro pode carregar mais de um defeito, então a taxa passa de cem quando a densidade é alta.',
      porObjeto: 'Por objeto',
      porDimensao: 'Por dimensão de qualidade',
      matriz: 'Objeto por dimensão',
      colObjeto: 'Objeto',
      colDimensao: 'Dimensão',
      colRegistros: 'Registros',
      colDefeitos: 'Defeitos',
      colTaxa: 'Taxa',
      colCriticos: 'Críticos',
      resumoPerfilados: 'registros perfilados',
      resumoDefeitos: 'defeitos',
      resumoCriticos: 'críticos',
      resumoTaxa: 'taxa geral',
    },
    intake: {
      title: 'Recebimento',
      note: 'Cada arquivo entregue pelo fornecedor de extração, com layout conferido, contagem lida do conteúdo e fingerprint. O recibo é emitido a partir do que foi lido, nunca do que foi declarado.',
      colArquivo: 'Arquivo',
      colSpe: 'SPE',
      colFormato: 'Formato',
      colLayout: 'Layout',
      colDeclarados: 'Declarados',
      colLidos: 'Lidos',
      colFingerprint: 'Fingerprint',
      colRecibo: 'Recibo',
      layoutOk: 'Validado',
      layoutDivergente: 'Divergente',
      reciboAceito: 'Aceito',
      reciboRessalva: 'Com ressalva',
      resumoArquivos: 'arquivos',
      resumoLayout: 'com layout validado',
      resumoContagem: 'com contagem divergente',
      resumoRegistros: 'registros lidos',
      emitidoPara: 'Recibo emitido a',
    },
    agents: {
      title: 'Agentes',
      note: 'Cada agente tem um revisor humano nomeado. Nenhum agente é accountable: quem assina é a pessoa.',
      revisorLabel: 'Revisor',
      regrasLabel: 'regras aplicadas',
      transversalLabel: 'Transversal — não ocupa passo',
    },
  },
  playbook: {
    title: 'GALAXY data playbook',
    subtitle: 'A regra vive aqui, versionada. Os agentes executam — não interpretam.',
    versaoCorrente: 'Versão corrente',
    checksumLabel: 'Checksum',
    referenciado: 'Referenciado em todo manifest de pacote',
    referenciadoNota:
      'O manifest de cada pacote carrega a versão e o checksum acima. É o que permite provar, depois da carga, qual regra gerou qual registro.',
    gerarDocumentacao: 'Gerar documentação',
    fecharDocumentacao: 'Fechar',
    documentacaoTitulo: 'Documentação gerada do playbook',
    documentacaoNota:
      'Este texto não é escrito à parte: sai das próprias regras, agora. A documentação exigida pelos critérios de aceite é gerada daqui — se a regra muda e o documento não muda junto, é porque alguém escreveu documentação fora do playbook.',
    resumo: {
      total: 'regras',
      ativas: 'ativas',
      candidatas: 'candidatas',
      deterministicas: 'determinísticas',
      generativas: 'generativas',
      aplicadas: 'aplicadas nesta onda',
    },
    filtros: {
      titulo: 'Filtros',
      agente: 'Agente',
      objeto: 'Objeto',
      tipo: 'Tipo',
      todos: 'Todos',
      limpar: 'Limpar filtros',
      resultado: 'regras no filtro',
    },
    tabela: {
      id: 'Regra',
      agente: 'Agente',
      objeto: 'Objeto',
      campo: 'Campo',
      tipo: 'Tipo',
      natureza: 'Natureza',
      status: 'Status',
      aplicada: 'Registros',
    },
    detalhe: {
      titulo: 'Detalhe da regra',
      vazio: 'Selecione uma regra para ver a expressão, a justificativa e o histórico.',
      expressao: 'Expressão',
      justificativa: 'Justificativa',
      dono: 'Dono',
      entrouEm: 'Entrou na versão',
      publicadaEm: 'Publicada na versão',
      criadaEm: 'Criada em',
      historico: 'Histórico de alterações',
      semHistorico: 'Sem alterações registradas além da criação.',
      aplicadaA: 'Aplicada a',
      registros: 'registros nesta onda',
      aplicacoes: 'aplicações no total',
      verRegistros: 'Registros afetados',
      naoAplicada: 'Não foi aplicada nesta onda.',
      candidataAviso:
        'Regra candidata: é proposta, não executa. Precisa ser promovida por um humano antes de rodar.',
    },
  },
  mapping: {
    title: 'Dicionário de mapeamento',
    subtitle: 'Campo a campo, do extrato do Nasajon para o tenant S/4HANA da Verene',
    objetoLabel: 'Objeto de migração',
    assinatura: {
      titulo: 'Estado de assinatura',
      sme: 'SAP SME',
      dataOwner: 'Verene data owner',
      gate: 'Gate 1',
      aprovado: 'Aprovou',
      assinado: 'Assinou',
      pendente: 'Pendente',
      recusado: 'Recusou',
      aviso: 'Nenhuma transformação roda sobre mapeamento não aprovado.',
      avisoNota:
        'A esteira para no checkpoint após o passo 3. Os passos 4 a 9 não executam — não é aviso de tela, é o motor.',
      aprovarSme: 'Aprovar como SAP SME',
      assinarOwner: 'Assinar no Gate 1',
      reverter: 'Reverter assinaturas',
    },
    tabela: {
      campoOrigem: 'Campo de origem',
      campoAlvo: 'Campo alvo S/4HANA',
      regra: 'Regra de conversão',
      valueDomain: 'Value domain (live tenant)',
      padrao: 'Default',
      dependencia: 'Dependência',
      excecao: 'Tratamento de exceção',
      obrigatorio: 'Obrigatório',
    },
    divergencia: {
      marca: 'Tenant Verene, não padrão SAP',
      titulo: 'Divergências do padrão SAP neste objeto',
      padraoSap: 'Padrão SAP',
      configVerene: 'Configuração Verene',
      impacto: 'Impacto na migração',
    },
    domain: {
      lidoDe: 'Lido da configuração ativa',
      entradas: 'entradas',
      semDominio: 'Campo livre',
    },
    semRegra: 'Atravessamento direto',
    semPadrao: 'Sem default',
    semDependencia: 'Sem dependência',
  },
} as const

export type Strings = typeof strings
