/**
 * Todo texto visível ao usuário vive aqui (regra 2 do CLAUDE.md).
 *
 * Nenhum componente em `src/` pode conter string literal renderizada em JSX.
 * Termos em inglês usados abaixo vêm de `glossary.ts` e não são traduzidos.
 */

export const strings = {
  app: {
    name: 'KEPLER',
    provider: 'Monoda Consulting Group',
    client: 'Verene Energia',
    descriptor: 'Plataforma agêntica de dados',
  },
  screens: {
    home: {
      wordmark: 'KEPLER',
    },
    styleguide: {
      title: 'Design system',
      subtitle: 'Tokens, superfícies e componentes do KEPLER',
      surfaceLabel: 'Superfície',
      surfaceInk: 'Escura (cockpit)',
      surfacePaper: 'Clara (documento)',
      sections: {
        palette: 'Paleta base',
        paletteNote:
          'Os nove valores do deck Galaxy. Imutáveis: componentes não usam estas cores diretamente, usam os tokens semânticos derivados delas.',
        semantic: 'Tokens semânticos',
        semanticNote:
          'Resolvem por superfície. verene-violet reprova sobre a superfície escura (2,36:1) e signal-green reprova sobre a clara (2,08:1) — por isso o token troca de valor, e não a regra de uso.',
        typography: 'Tipografia',
        typographyNote:
          'Jost, geométrica, substituta web da Century Gothic do deck. Números sempre tabulares.',
        buttons: 'Botões',
        badges: 'Estados',
        badgesNote: 'Matizes quentes e o neutro frio marcam situação. Sempre com rótulo — cor nunca é o único portador de significado.',
        defects: 'Origem de defeito',
        defectsNote:
          'Escala categórica em matizes frios, separada por matiz e por luminância. Distinta da escala de estado, que é quente.',
        table: 'Tabela densa',
        tableNote: 'Linha de 28px, números tabulares, alinhamento à direita em toda coluna numérica.',
        logos: 'Logos',
        logosNote: 'Slots reservados. Os arquivos atuais são placeholders e seguem a cor da superfície.',
      },
      table: {
        columns: {
          object: 'Objeto',
          records: 'Registros',
          migrated: 'Migrados',
          defects: 'Defeitos',
          rate: 'Aderência',
          origin: 'Origem',
          state: 'Situação',
        },
      },
      typeSamples: {
        pageTitle: 'Título de tela',
        sectionTitle: 'Título de seção',
        body: 'Texto corrido em corpo de 13px, a medida padrão da interface.',
        small: 'Texto de apoio em 12px',
        label: 'RÓTULO EM 11PX',
        micro: 'MICRO 10PX',
        numerals: 'Numerais tabulares',
        // dois runs de mesmo comprimento: com tnum as colunas coincidem
        numeralsSampleA: '1234567890',
        numeralsSampleB: '1111111111',
      },
      buttonSamples: {
        primary: 'Executar playbook',
        secondary: 'Ver manifest',
        ghost: 'Cancelar',
        disabled: 'Indisponível',
      },
      swatch: {
        onInk: 'sobre escura',
        onPaper: 'sobre clara',
        contrast: 'contraste',
      },
    },
  },
  states: {
    signed: 'Assinado',
    held: 'Retido',
    exception: 'Exceção aberta',
    'pending-gate': 'Aguardando Gate',
  },
  defectOrigins: {
    'source-extract': 'Origem do extrato',
    transformation: 'Transformação',
    'target-config': 'Configuração do destino',
    'load-execution': 'Execução da carga',
  },
  severidades: {
    critical: 'Crítica',
    'non-critical': 'Não crítica',
  },
  defects: {
    'defect-source': 'Origem',
    'defect-transformation': 'Transformação',
    'defect-target-config': 'Configuração de destino',
    'defect-load': 'Carga',
  },
  brands: {
    verene: 'Verene Energia',
    monoda: 'Monoda Consulting Group',
  },
  // Símbolos e separadores também são texto visível: entram aqui, não no JSX.
  simbolos: {
    porcento: '%',
    separador: ' · ',
    doisPontos: ': ',
    intervalo: ' — ',
  },
  shell: {
    projectTitle: 'GALAXY | Transformação de Dados',
    playbookLabel: 'playbook',
    cycleLabel: 'Ciclo',
    navLabel: 'Telas',
    skipToContent: 'Ir para o conteúdo',
    // Sempre visível, em toda tela. Nunca pode haver dúvida de que não é produtivo.
    demo: 'Ambiente de demonstração',
    demoDetalhe: 'dados sintéticos',
  },
  nav: {
    missionControl: 'Mission Control',
    gates: 'Gates',
    candidate: 'Regra candidata',
    playbook: 'Playbook',
    mapping: 'Dicionário de mapeamento',
    record: 'Rastreabilidade',
    packages: 'Pacotes de carga',
    reconciliation: 'Reconciliação',
    duplicates: 'Fila de duplicatas',
    exceptions: 'Fila de exceções',
    styleguide: 'Design system',
  },
  outcomes: {
    migrated: 'Migrado',
    reused: 'Reusado',
    merged: 'Fundido',
    held: 'Retido',
  },
  stepNames: {
    receive: 'RECEIVE',
    profile: 'PROFILE',
    map: 'MAP',
    transform: 'TRANSFORM',
    deduplicate: 'DEDUPLICATE',
    enrich: 'ENRICH',
    validate: 'VALIDATE',
    package: 'PACKAGE',
    reconcile: 'RECONCILE',
  },
  stepStatus: {
    completed: 'Concluído',
    blocked: 'Bloqueado',
    'not-reached': 'Não alcançado',
  },
  ruleTypes: {
    format: 'Formato',
    domain: 'Domínio',
    length: 'Comprimento',
    referential: 'Referencial',
    conversion: 'Conversão',
    derivation: 'Derivação',
    business: 'Negócio',
    survivorship: 'Sobrevivência',
  },
  ruleStatus: {
    active: 'Ativa',
    candidate: 'Candidata',
    deprecated: 'Aposentada',
  },
  ruleNature: {
    deterministic: 'Determinística',
    generative: 'Generativa',
  },
  migrationObjects: {
    'business-partner': 'Business Partner (fornecedor)',
    'product-master': 'Product master',
    'service-master': 'Service master',
    'outline-agreement': 'Outline agreement',
    'purchase-order': 'Purchase order',
    'purchase-requisition': 'Purchase requisition',
    stock: 'Posições de estoque',
  },
  packageStates: {
    'nao-iniciado': 'Não iniciado',
    'em-processamento': 'Em processamento',
    retido: 'Retido',
    'aguardando-gate': 'Aguardando Gate',
    aprovado: 'Aprovado',
  },
  qualityDimensions: {
    completude: 'Completude',
    validade: 'Validade',
    unicidade: 'Unicidade',
    consistencia: 'Consistência',
    conformidade: 'Conformidade',
    precisao: 'Precisão',
  },
  agentActivity: {
    concluido: 'Concluído',
    'em-execucao': 'Em execução',
    bloqueado: 'Bloqueado',
    aguardando: 'Aguardando',
    continuo: 'Contínuo',
  },
  missionControl: {
    title: 'Mission Control',
    subtitle: 'Escopo, recebimento, qualidade e agentes em um lugar só',
    grid: {
      title: 'Pacotes de carga',
      note: 'Seis objetos, quatro SPEs, dois ciclos. Quarenta e oito pacotes — este é o escopo inteiro, não uma amostra. O número em cada célula é o volume previsto do pacote.',
      colObjeto: 'Objeto',
      colTotal: 'Volume',
      legenda: 'Estado',
      resumoPacotes: 'pacotes',
      resumoRegistros: 'registros no escopo',
    },
    waves: {
      title: 'Plano de ondas',
      note: 'A ordem não é arbitrária: documento transacional aponta para cadastro. Migrar fora de ordem é criar referência para o que ainda não existe.',
      objetosLabel: 'Objetos',
      dependenciaLabel: 'Por que nesta posição',
      volumeLabel: 'Volume',
      waveLabel: 'Wave',
    },
    defects: {
      title: 'Mapa de defeitos',
      note: 'Perfilagem do VEGA sobre o que já foi recebido. Taxa é defeitos por cem registros; um registro pode carregar mais de um defeito, então a taxa passa de cem quando a densidade é alta.',
      porObjeto: 'Por objeto',
      porDimensao: 'Por dimensão de qualidade',
      matriz: 'Objeto por dimensão',
      colObjeto: 'Objeto',
      colDimensao: 'Dimensão',
      colRegistros: 'Registros',
      colDefeitos: 'Defeitos',
      colTaxa: 'Taxa',
      colCriticos: 'Críticos',
      resumoPerfilados: 'registros perfilados',
      resumoDefeitos: 'defeitos',
      resumoCriticos: 'críticos',
      resumoTaxa: 'taxa geral',
    },
    intake: {
      title: 'Recebimento',
      note: 'Cada arquivo entregue pelo fornecedor de extração, com layout conferido, contagem lida do conteúdo e fingerprint. O recibo é emitido a partir do que foi lido, nunca do que foi declarado.',
      colArquivo: 'Arquivo',
      colSpe: 'SPE',
      colFormato: 'Formato',
      colLayout: 'Layout',
      colDeclarados: 'Declarados',
      colLidos: 'Lidos',
      colFingerprint: 'Fingerprint',
      colRecibo: 'Recibo',
      layoutOk: 'Validado',
      layoutDivergente: 'Divergente',
      reciboAceito: 'Aceito',
      reciboRessalva: 'Com ressalva',
      resumoArquivos: 'arquivos',
      resumoLayout: 'com layout validado',
      resumoContagem: 'com contagem divergente',
      resumoRegistros: 'registros lidos',
      emitidoPara: 'Recibo emitido a',
    },
    agents: {
      title: 'Agentes',
      note: 'Cada agente tem um revisor humano nomeado. Nenhum agente é accountable: quem assina é a pessoa.',
      revisorLabel: 'Revisor',
      regrasLabel: 'regras aplicadas',
      transversalLabel: 'Transversal — não ocupa passo',
    },
  },
  playbook: {
    title: 'GALAXY data playbook',
    subtitle: 'A regra vive aqui, versionada. Os agentes executam — não interpretam.',
    versaoCorrente: 'Versão corrente',
    checksumLabel: 'Checksum',
    referenciado: 'Referenciado em todo manifest de pacote',
    referenciadoNota:
      'O manifest de cada pacote carrega a versão e o checksum acima. É o que permite provar, depois da carga, qual regra gerou qual registro.',
    gerarDocumentacao: 'Gerar documentação',
    fecharDocumentacao: 'Fechar',
    documentacaoTitulo: 'Documentação gerada do playbook',
    documentacaoNota:
      'Este texto não é escrito à parte: sai das próprias regras, agora. A documentação exigida pelos critérios de aceite é gerada daqui — se a regra muda e o documento não muda junto, é porque alguém escreveu documentação fora do playbook.',
    resumo: {
      total: 'regras',
      ativas: 'ativas',
      candidatas: 'candidatas',
      deterministicas: 'determinísticas',
      generativas: 'generativas',
      aplicadas: 'aplicadas nesta onda',
    },
    filtros: {
      titulo: 'Filtros',
      agente: 'Agente',
      objeto: 'Objeto',
      tipo: 'Tipo',
      todos: 'Todos',
      limpar: 'Limpar filtros',
      resultado: 'regras no filtro',
    },
    tabela: {
      id: 'Regra',
      agente: 'Agente',
      objeto: 'Objeto',
      campo: 'Campo',
      tipo: 'Tipo',
      natureza: 'Natureza',
      status: 'Status',
      aplicada: 'Registros',
    },
    detalhe: {
      titulo: 'Detalhe da regra',
      vazio: 'Selecione uma regra para ver a expressão, a justificativa e o histórico.',
      expressao: 'Expressão',
      justificativa: 'Justificativa',
      dono: 'Dono',
      entrouEm: 'Entrou na versão',
      publicadaEm: 'Publicada na versão',
      criadaEm: 'Criada em',
      historico: 'Histórico de alterações',
      semHistorico: 'Sem alterações registradas além da criação.',
      aplicadaA: 'Aplicada a',
      registros: 'registros nesta onda',
      aplicacoes: 'aplicações no total',
      verRegistros: 'Registros afetados',
      naoAplicada: 'Não foi aplicada nesta onda.',
      candidataAviso:
        'Regra candidata: é proposta, não executa. Precisa ser promovida por um humano antes de rodar.',
    },
  },
  correcao: {
    titulo: 'Correção proposta para esta regra',
    nota: 'A regra não se edita no lugar: uma redação nova é publicada em uma versão nova, e a onda passa a rodar sobre ela quando alguém decide adotá-la. É por isso que corrigir aqui não apaga o que já foi assinado — muda o que vale daqui para a frente.',
    parametro: 'Parâmetro',
    vigente: 'Vigente agora',
    corrigido: 'Corrigido',
    publicadaEm: 'Publicada na versão',
    autor: 'Autor da correção',
    afetados: 'registros que a correção muda',
    excecoesFecham: 'exceções que se fecham',
    publicar: 'Corrigir e publicar',
    jaAdotada: 'Esta é a redação vigente na onda.',
    expressaoAntes: 'Expressão vigente',
    expressaoDepois: 'Expressão corrigida',
  },
  propagacao: {
    titulo: 'Propagação',
    nota: 'A recomputação é instantânea: a sequência abaixo mostra por onde a correção passou, não quanto tempo ela levou. O ganho não está no processador — está em não haver ninguém no meio do caminho.',
    abrir: 'Abrir',
    nos: {
      regra: 'Regra corrigida',
      playbook: 'Playbook selado',
      onda: 'Onda regerada',
      pacote: 'Pacote refeito',
      manifest: 'Manifest novo',
    },
    detalhe: {
      checksum: 'checksum',
      retocados: 'registros retocados',
      campos: 'campos',
      excecoesFechadas: 'exceções fechadas',
      retidosLiberados: 'retidos que voltaram ao pacote',
      registros: 'registros',
      aguardaG4: 'aguarda reassinatura no G4',
    },
    fechar: 'Fechar',
  },
  mapping: {
    title: 'Dicionário de mapeamento',
    subtitle: 'Campo a campo, do extrato do Nasajon para o tenant S/4HANA da Verene',
    objetoLabel: 'Objeto de migração',
    assinatura: {
      titulo: 'Estado de assinatura',
      sme: 'SAP SME',
      dataOwner: 'Verene data owner',
      gate: 'Gate 1',
      aprovado: 'Aprovou',
      assinado: 'Assinou',
      pendente: 'Pendente',
      recusado: 'Recusou',
      aviso: 'Nenhuma transformação roda sobre mapeamento não aprovado.',
      avisoNota:
        'A esteira para no checkpoint após o passo 3. Os passos 4 a 9 não executam — não é aviso de tela, é o motor.',
      aprovarSme: 'Aprovar como SAP SME',
      assinarOwner: 'Assinar no Gate 1',
      reverter: 'Reverter assinaturas',
    },
    tabela: {
      campoOrigem: 'Campo de origem',
      campoAlvo: 'Campo alvo S/4HANA',
      regra: 'Regra de conversão',
      valueDomain: 'Value domain (live tenant)',
      padrao: 'Default',
      dependencia: 'Dependência',
      excecao: 'Tratamento de exceção',
      obrigatorio: 'Obrigatório',
    },
    divergencia: {
      marca: 'Tenant Verene, não padrão SAP',
      titulo: 'Divergências do padrão SAP neste objeto',
      padraoSap: 'Padrão SAP',
      configVerene: 'Configuração Verene',
      impacto: 'Impacto na migração',
    },
    domain: {
      lidoDe: 'Lido da configuração ativa',
      entradas: 'entradas',
      semDominio: 'Campo livre',
    },
    semRegra: 'Atravessamento direto',
    semPadrao: 'Sem default',
    semDependencia: 'Sem dependência',
  },
  record: {
    title: 'Rastreabilidade do registro',
    subtitle: 'Do valor de origem ao valor final, campo a campo, com a regra que alterou cada um',
    casosLabel: 'Caso',
    casoFornecedor: 'Fornecedor',
    casoLinhaContrato: 'Linha de contrato',
    casoNota:
      'Dois objetos, a mesma esteira: o cadastro simples e a linha de contrato, que é o objeto de maior densidade de regra do escopo.',
    origem: 'Valor de origem',
    destino: 'Valor final',
    semDestino: 'Sem valor final: o registro está retido.',
    timeline: 'Esteira',
    trilha: 'Trilha campo a campo',
    colSeq: '#',
    colPasso: 'Passo',
    colAgente: 'Agente',
    colCampo: 'Campo',
    colAntes: 'Antes',
    colDepois: 'Depois',
    colRegra: 'Regra',
    colVersao: 'Versão',
    colInstante: 'Instante',
    colNota: 'Observação',
    vazio: 'vazio',
    semRegraNoPasso: 'Nenhuma regra se aplica a este objeto neste passo.',
    excecoes: 'Exceções abertas neste registro',
    aplicacoes: 'aplicações de regra',
    camposTocados: 'campos tocados',
    verNoPlaybook: 'Abrir no playbook',
    clusterLabel: 'Cluster de duplicata',
    resolvidoPara: 'Resolvido para',
  },
  duplicates: {
    title: 'Fila de duplicatas',
    subtitle: 'Clusters propostos pelo ATLAS, confirmados um a um por gente',
    nuncaAutomatico: 'O merge nunca é automático.',
    nuncaAutomaticoNota:
      'O ATLAS propõe o cluster e o sobrevivente. Nada é fundido sem confirmação individual — não há aprovação em lote, e a esteira fica bloqueada no checkpoint enquanto houver cluster sem decisão.',
    scoreLabel: 'Score do match',
    racional: 'Racional do match',
    peso: 'peso',
    bate: 'confere',
    naoBate: 'não confere',
    divergentes: 'Campos que divergem',
    iguais: 'Campos idênticos',
    survivorship: 'Regra de sobrevivência proposta',
    sobrevivente: 'Sobrevivente',
    aposentado: 'Aposentado',
    crossRef: 'Cross-reference mantida',
    crossRefNota: 'O código aposentado continua visível apontando para o sobrevivente. Não some do sistema.',
    acoes: 'Ações',
    confirmar: 'Confirmar merge',
    rejeitar: 'Rejeitar: não são a mesma empresa',
    dividir: 'Dividir cluster',
    decidido: 'Decisão registrada',
    pendente: 'Aguardando decisão',
    reverter: 'Reverter decisões',
    reuso: {
      titulo: 'Já cadastrados na base Verene',
      alerta: 'Já cadastrado na base Verene — reutilizar, não recriar',
      nota: 'Estes documentos já existem como Business Partner no tenant. Não são cluster de duplicata entre SPEs: são cadastro que já existe no destino.',
      businessPartner: 'Business Partner existente',
      criadoEm: 'Criado em',
    },
    semClusters: 'Nenhum cluster para revisar.',
    bloqueadoTitulo: 'A esteira ainda não chegou ao passo 5.',
    bloqueadoNota: 'A deduplicação roda depois do mapeamento aprovado. Enquanto o SAP SME e o data owner não assinarem, não há cluster para revisar — a fila estar vazia aqui é o checkpoint funcionando.',
    irParaMapeamento: 'Ir para o dicionário de mapeamento',
    escopoNota: 'A fila olha as quatro SPEs juntas: duplicata entre cadastros só existe cruzando SPE.',
    verTodasSpes: 'Ver todas as SPEs',
  },
  exceptions: {
    title: 'Fila de exceções',
    subtitle: 'Registros retidos, classificados e roteados a um dono nomeado',
    semDefault: 'Nada é defaultado para o lote passar.',
    semDefaultNota:
      'Não existe aplicar valor padrão nesta tela, de propósito. As opções são liberar com decisão registrada ou manter retido. Preencher por padrão é o que produz base suja com aparência de limpa.',
    tecnica: 'Técnica',
    negocio: 'Negócio',
    tecnicaNota: 'Decisão de configuração ou estrutura — vai para o SAP SME.',
    negocioNota: 'Decisão sobre o significado do dado — vai para o data owner da Verene.',
    colRegistro: 'Registro',
    colExcecao: 'Exceção',
    colOrigem: 'Origem',
    colClasse: 'Classe',
    colDono: 'Dono',
    colPrazo: 'Prazo',
    colEstado: 'Estado',
    estados: {
      aberta: 'Aberta',
      liberada: 'Liberada',
      'mantida-retida': 'Mantida retida',
    },
    colAcoes: 'Ações',
    liberar: 'Liberar',
    manterRetido: 'Manter retido',
    reverter: 'Reverter decisões',
    encaminhadaA: 'Encaminhada a',
    prazoDias: 'dias úteis',
    resumo: {
      total: 'exceções',
      abertas: 'abertas',
      tecnicas: 'técnicas',
      negocio: 'de negócio',
      criticas: 'críticas',
    },
    enriquecimento: {
      titulo: 'Enriquecimento proposto pelo NOVA',
      nota: 'Todo valor proposto vem com a evidência de onde saiu, anexada. Sem evidência, sem proposta — e a tela diz por que não houve.',
      valorProposto: 'Valor proposto',
      evidencia: 'Evidência',
      fonte: 'Fonte',
      referencia: 'Referência',
      semProposta: 'Sem proposta',
      regraLabel: 'Regra',
      campoLabel: 'Campo',
    },
    vazia: 'Nenhuma exceção aberta.',
    bloqueadoTitulo: 'A esteira ainda não chegou ao passo 7.',
    bloqueadoNota: 'A validação roda depois do mapeamento aprovado e de cada cluster de duplicata confirmado. A fila estar vazia aqui não é tela sem dado — é o checkpoint segurando.',
    irParaMapeamento: 'Ir para o dicionário de mapeamento',
    irParaDuplicatas: 'Ir para a fila de duplicatas',
    escopoNota: 'A fila olha as quatro SPEs juntas.',
  },
  packages: {
    title: 'Pacotes de carga',
    subtitle: 'O artefato que vai para o time de carga, com manifest, checksum e simulação aprovada',
    objetoLabel: 'Objeto',
    colObjeto: 'Objeto',
    colSpe: 'SPE',
    colTeste: 'Ciclo de teste',
    colCutover: 'Cutover de produção',
    colVolume: 'Volume',
    colSimulacao: 'Simulação no cockpit',
    detalheLabel: 'Detalhe do pacote',
    xml: {
      titulo: 'Preview do XML do Migration Cockpit',
      nota: 'Gerado dos registros de fato, agora. Não é exemplo colado: o cabeçalho carrega a versão e o checksum do playbook que produziu estes valores.',
      registrosNoPreview: 'primeiros registros',
      bytesPorRegistro: 'bytes por registro',
    },
    conformidade: {
      titulo: 'Conformidade',
      nota: 'Conferido campo a campo contra a configuração do tenant, não contra o SAP padrão.',
      ok: 'Conforme',
      falha: 'Não conforme',
      naoVerificado: 'Não verificado',
      afetados: 'Registros afetados',
    },
    split: {
      titulo: 'Divisão do pacote',
      nota: 'Dois tetos: 100 MB por arquivo e 500 registros por lote. Vale o menor dos dois.',
      colParte: 'Arquivo',
      colRegistros: 'Registros',
      colTamanho: 'Tamanho',
      colChecksum: 'Checksum',
      totalLabel: 'Total estimado',
      limitanteTamanho: 'Divisão determinada pelo limite de tamanho.',
      limitanteRegistros: 'Divisão determinada pelo limite de registros por lote.',
      limitanteNenhum: 'Cabe em um arquivo só.',
    },
    manifest: {
      titulo: 'Manifest',
      playbookVersion: 'Versão do playbook',
      playbookChecksum: 'Checksum do playbook',
      datasetChecksum: 'Checksum do conteúdo',
      total: 'Registros',
      geradoEm: 'Gerado em',
      laco: 'Mesma versão e mesmo checksum do playbook. É por aqui que se prova, depois da carga, qual regra gerou qual registro.',
      verPlaybook: 'Abrir o playbook',
    },
    entrega: {
      titulo: 'Entrega formal ao time de carga',
      nota: 'O pacote não é mandado por e-mail: é entregue com escopo, versão, exceções conhecidas e calendário. É o documento que responde depois à pergunta "isto foi combinado?".',
      destinatario: 'Destinatário',
      escopo: 'Escopo declarado',
      versao: 'Versão do playbook',
      excecoes: 'Exceções conhecidas declaradas',
      semExcecoes: 'Nenhuma exceção conhecida neste pacote.',
      calendario: 'Calendário acordado',
      registros: 'registros',
      objetos: 'objetos',
    },
    simulacao: {
      titulo: 'Simulação no Migration Cockpit',
      nota: 'Pacote que não passou na simulação não é liberado.',
      aprovada: 'Aprovada',
      reprovada: 'Reprovada',
      'nao-executada': 'Não executada',
      executadaEm: 'Executada em',
      registrosSimulados: 'registros simulados',
      liberado: 'Liberado para carga',
      naoLiberado: 'Não liberado',
    },
  },
  reconciliation: {
    title: 'Reconciliação',
    subtitle: 'Origem contra destino, em contagem e em valor, com toda diferença explicada',
    porContagem: 'Por contagem',
    porValor: 'Por valor',
    valorNota: 'Valor só existe onde há montante: contratos. Fornecedor é cadastro — inventar um valor para preencher a tela seria o tipo de número que não sobrevive a uma pergunta.',
    colChave: 'Recorte',
    colOrigem: 'Origem',
    colDestino: 'Destino',
    colDiferenca: 'Diferença',
    colExplicacao: 'Explicação da diferença',
    fecha: 'Fecha',
    naoFecha: 'Não fecha',
    semDiferenca: 'Sem diferença.',
    registro: {
      titulo: 'Registro de defeitos por origem',
      nota: 'As quatro origens da taxonomia, com o dono contratual de cada uma. Só a origem transformation é responsabilidade da Monoda — nas outras três a Monoda detecta, evidencia e roteia.',
      monoda: 'Responsabilidade Monoda',
      outros: 'Responsabilidade de terceiros',
      colOrigem: 'Origem',
      colDono: 'Dono contratual',
      colTotal: 'Total',
      colCriticos: 'Críticos',
      colNaoCriticos: 'Não críticos',
      colPercentual: 'Sobre o escopo',
      semDefeito: 'Nenhum defeito nesta origem.',
      detalhe: 'Tipos de defeito',
    },
    placar: {
      titulo: 'Placar dos critérios de aceite',
      nota: 'Cada critério com o Gate onde é medido. Os dois critérios de defeito medem apenas a origem transformation.',
      colCriterio: 'Critério',
      colGate: 'Gate',
      colAlvo: 'Alvo',
      colMedido: 'Medido',
      colResultado: 'Resultado',
      atende: 'Atende',
      naoAtende: 'Não atende',
      naoMensuravel: 'Ainda não mensurável',
      comoMedido: 'Como foi medido',
      naoMensuravelNota: 'A esteira ainda não alcançou o passo que produz esta medida.',
    },
    fiori: {
      titulo: 'Verificação guiada nos apps Fiori',
      nota: 'Contagem prova que o número fecha; não prova que o registro está certo. A verificação no app fecha essa lacuna e vira evidência do Gate.',
      app: 'App',
      registroExemplo: 'Registro a abrir',
      gateLabel: 'Evidência do',
      passos: 'Passos',
      campo: 'Campo',
      marcarVerificado: 'Registrar verificação',
      verificado: 'Verificado',
      verificadoPor: 'Verificado por',
      pendente: 'Pendente',
    },
  },
  gates: {
    title: 'Gates',
    subtitle: 'Oito pontos de decisão, cada um com artefato assinado, evidência entregue e aprovador nomeado',
    railLabel: 'Sequência dos Gates',
    resumo: {
      aprovado: { um: 'aprovado', varios: 'aprovados' },
      'em-avaliacao': { um: 'em avaliação', varios: 'em avaliação' },
      'evidencia-pendente': { um: 'com evidência pendente', varios: 'com evidência pendente' },
      'entrada-recusada': { um: 'com entrada recusada', varios: 'com entrada recusada' },
    },
    status: {
      aprovado: 'Aprovado',
      'em-avaliacao': 'Em avaliação',
      'evidencia-pendente': 'Evidência pendente',
      'entrada-recusada': 'Entrada recusada',
    },
    quandoOcorre: 'Quando ocorre',
    oQueEAprovado: 'O que é aprovado',
    artefatoLabel: 'Artefato aprovado neste Gate',
    checkpointLabel: 'Checkpoint da esteira',
    semCheckpoint: 'Fora da esteira',
    recusa: {
      titulo: 'Entrada recusada',
      frase: 'Este Gate não abre. O artefato do Gate anterior não está assinado.',
      artefatoLabel: 'Artefato que falta',
      assinadoNo: 'Assinado no',
      consequencia:
        'Não abre com ressalva, não abre em paralelo, não abre "enquanto isso". A recusa some quando a assinatura aparece — não antes.',
    },
    trilha: {
      titulo: 'Trilha de assinatura do artefato',
      nota: 'Quem assinou, quando, e sobre qual versão de playbook. Sem a versão, "revisado e assinado" não diz o que foi revisado: a regra pode ter mudado depois.',
      colOQue: 'O que assina',
      colResponsavel: 'Responsável',
      colDecisao: 'Decisão',
      colQuando: 'Quando',
      colVersao: 'Versão do playbook',
      naoAssinado: 'Não assinado',
      approved: 'Aprovado',
      rejected: 'Rejeitado',
      deQuantas: 'de',
      assinaturas: 'assinaturas',
      semResponsavel: 'Área sem responsável nomeado',
    },
    evidencia: {
      titulo: 'Evidência entregue ao Gate',
      nota: 'Cada uma abre na tela onde ela vive. Evidência que não dá para abrir na hora não é evidência, é afirmação.',
      disponivel: 'Entregue',
      indisponivel: 'Ainda não produzida',
      abrir: 'Abrir',
    },
    pendencias: {
      titulo: 'O que falta para decidir',
      assinatura: 'Assinatura pendente',
      clusters: 'Cluster(s) de duplicata sem decisão',
      excecoes: 'Exceção(ões) sem decisão',
      evidencia: 'Evidência ainda não produzida',
      versao: 'Assinatura dada sobre outra versão do playbook',
      nenhuma: 'Nada pendente.',
    },
    acao: {
      assinar: 'Assinar o Gate',
      rejeitar: 'Rejeitar',
      assinadoPor: 'Assinado por',
      noutraTela: 'Este Gate é assinado onde a evidência é revisada.',
      irAssinar: 'Ir até a evidência',
      recusada: 'Entrada recusada: não há o que assinar aqui.',
      evidenciaFalta: 'Evidência incompleta. Assinar agora seria assinar o que ainda não existe.',
    },
    reset: 'Reiniciar demonstração',
    paymentLink: 'Liberação de pagamento',
  },
  gatesPayment: {
    title: 'Liberação de pagamento',
    subtitle: 'Cada parcela atada ao Gate que a libera',
    nota: 'Percentual do valor do contrato. O valor absoluto não vive no protótipo: número inventado ao lado de percentual real seria pior do que não mostrar valor nenhum.',
    colGate: 'Gate',
    colParcela: 'Parcela',
    colEstado: 'Estado',
    colOQueLibera: 'O que a parcela remunera',
    liberada: 'Liberada',
    retida: 'Retida',
    totalLiberado: 'Liberado',
    totalRetido: 'Retido',
    bloqueioPor: 'Bloqueada pela entrada recusada em',
    semParcela: 'Sem parcela',
    semParcelaNota:
      'G0, G3 e G5 não liberam parcela. Nem todo ponto de decisão é ponto de faturamento — e um Gate sem dinheiro atrás continua sendo bloqueante.',
    voltar: 'Voltar aos Gates',
  },
  candidate: {
    title: 'Regra candidata',
    subtitle: 'O padrão que o agente evidencia — e o limite do que ele consegue afirmar',
    limite:
      'Um agente consegue evidenciar que uma regra provavelmente existe. Ele não consegue confirmar que a regra está correta.',
    limiteNota:
      'Por isso este caso não vira código. Ele vira fila, com dono, prazo e três saídas — e nenhuma delas é o agente decidindo sozinho.',
    evidencia: {
      titulo: 'A evidência',
      nota: 'Os cadastros do mesmo prestador em SPEs diferentes, campo a campo. As linhas destacadas são as que divergem; o resto é idêntico, e é isso que descarta as explicações fáceis.',
      colCampo: 'Campo',
      documento: 'CPF',
      igualNosDois: 'Igual nos dois cadastros',
      divergente: 'Diverge',
      abrirRegistro: 'Abrir a rastreabilidade',
    },
    frequencia: {
      titulo: 'A frequência',
      nota: 'Um caso isolado é erro de digitação. Dois em dois é padrão — e é a frequência que separa um do outro.',
      pessoasFisicas: 'PF no escopo',
      comCadastroEmMaisDeUmaSpe: 'com o mesmo CPF em mais de uma SPE',
      divergentes: 'divergem no tratamento de retenção',
      registrosEnvolvidos: 'registros envolvidos',
      spesEnvolvidas: 'SPEs envolvidas',
      percentual: 'do recorte que a regra alcança',
    },
    inferencia: {
      titulo: 'A inferência',
      regraTitulo: 'A regra candidata no playbook',
      expressao: 'Expressão',
      justificativa: 'Por que ela existe',
      dona: 'Dona da regra',
      naoExecuta: 'Candidata: não executa. KANON recusa regra não promovida — é a R-GOV-004.',
      hipoteseTitulo: 'A hipótese do modelo',
      hipoteseNota: 'Esta é a única tela do protótipo que faz chamada de rede. O texto abaixo é gerado a partir dos mesmos quatro registros — não entra na esteira, não entra em checksum, não gera pacote.',
      enunciado: 'Hipótese',
      evidenciaCitada: 'Evidência citada',
      naoConfirmavel: 'O que o modelo não consegue confirmar',
      consultando: 'Consultando o modelo',
      consultarDeNovo: 'Consultar de novo',
      origemAoVivo: 'gerado ao vivo',
      origemReferencia: 'resposta de referência',
      modelo: 'Modelo',
    },
    contencao: {
      titulo: 'Regra candidata — aguardando confirmação da Verene',
      nota: 'Confirmar não executa a regra. A promoção de candidata a ativa é ato de KANON, numa nova versão selada do playbook — o que se registra aqui é a decisão do dono do processo.',
      dono: 'Dono da decisão',
      area: 'Área',
      prazo: 'Prazo',
      severidade: 'Severidade',
      confirmar: 'Confirmar a regra',
      rejeitar: 'Rejeitar',
      reformular: 'Reformular',
      decidida: 'Decisão registrada',
      confirmada: 'Confirmada pelo dono do processo',
      rejeitada: 'Rejeitada pelo dono do processo',
      reformular_: 'Devolvida para reformulação',
      efeito: 'A regra continua candidata nesta versão. A promoção entra na próxima versão selada.',
      em: 'em',
      sobre: 'sobre',
    },
  },
  apresentacao: {
    titulo: 'Modo de apresentação',
    roteiro: 'Roteiro',
    passoDe: 'de',
    previsto: 'previsto',
    total: 'roteiro',
    fraseChave: 'Frase-chave',
    acoes: 'Na tela',
    notas: 'Se perguntarem',
    proximo: 'Próximo passo',
    ultimo: 'Último passo do roteiro',
    abrirNotas: 'Notas',
    fecharNotas: 'Fechar notas',
    somenteApresentador:
      'Painel do apresentador. Se a tela estiver espelhada para o cliente, feche antes de continuar.',
    atalhos: {
      titulo: 'Atalhos',
      passos: 'passo anterior e seguinte',
      notas: 'notas do apresentador',
      reset: 'reiniciar a demonstração do zero',
      sair: 'sair do modo de apresentação',
      ligar: 'ligar o modo de apresentação',
    },
    dica: 'Pressione P para conduzir a demonstração por um roteiro.',
  },
} as const

export type Strings = typeof strings
